// Generated by tests/compat/frida_surface.py; do not edit manually.
(function () {
    "use strict";

    var requiredGlobals = [{"name":"console","type":"object","classification":"compatible"},{"name":"ptr","type":"function","classification":"compatible"},{"name":"NULL","type":"object","classification":"compatible"},{"name":"Memory","type":"object","classification":"partial"},{"name":"File","type":"function","classification":"partial"},{"name":"Process","type":"object","classification":"partial"},{"name":"Module","type":"object","classification":"legacy"},{"name":"Hook","type":"object","classification":"extension"},{"name":"Interceptor","type":"object","classification":"partial"},{"name":"Stalker","type":"object","classification":"partial"},{"name":"CModule","type":"function","classification":"partial"},{"name":"NativeFunction","type":"function","classification":"partial"},{"name":"hook","type":"function","classification":"extension"},{"name":"hookNative","type":"function","classification":"extension"},{"name":"attachNative","type":"function","classification":"extension"},{"name":"unhook","type":"function","classification":"extension"},{"name":"callNative","type":"function","classification":"extension"},{"name":"recompHook","type":"function","classification":"extension"},{"name":"Java","type":"object","classification":"partial"},{"name":"Jni","type":"object","classification":"extension"},{"name":"rpc","type":"object","classification":"compatible"}];
    var optionalGlobals = [{"name":"qbdi","type":"object","classification":"extension","feature":"qbdi"}];
    var probes = [{"path":"console.log","type":"function"},{"path":"NULL.isNull","type":"function"},{"path":"Memory.alloc","type":"function"},{"path":"Memory.copy","type":"function"},{"path":"Memory.dup","type":"function"},{"path":"Memory.protect","type":"function"},{"path":"Memory.queryProtection","type":"function"},{"path":"Memory.scanSync","type":"function"},{"path":"Memory.flushCodeCache","type":"function"},{"path":"File.readAllBytes","type":"function"},{"path":"File.writeAllBytes","type":"function"},{"path":"Process.id","type":"number"},{"path":"Process.arch","type":"string"},{"path":"Process.pointerSize","type":"number"},{"path":"Process.enumerateModules","type":"function"},{"path":"Process.enumerateThreads","type":"function"},{"path":"Process.findModuleByName","type":"function"},{"path":"Module.findExportByName","type":"function"},{"path":"Module.enumerateExports","type":"function"},{"path":"Module.enumerateSymbols","type":"function"},{"path":"Interceptor.attach","type":"function"},{"path":"Interceptor.replace","type":"function"},{"path":"Interceptor.revert","type":"function"},{"path":"Interceptor.flush","type":"function"},{"path":"Stalker.supported","type":"boolean"},{"path":"Stalker.follow","type":"function"},{"path":"Stalker.addCallProbe","type":"function"},{"path":"Stalker.parse","type":"function"},{"path":"Hook.NORMAL","type":"number"},{"path":"Hook.WXSHADOW","type":"number"},{"path":"Java.use","type":"function"},{"path":"Java.ready","type":"function"},{"path":"Java.choose","type":"function"},{"path":"Java.enumerateClassLoadersSync","type":"function"},{"path":"Jni.addr","type":"function"},{"path":"rpc.exports","type":"object"}];

    function resolve(path) {
        var value = globalThis;
        var parts = path.split(".");
        for (var index = 0; index !== parts.length; index++) {
            if (value === null || value === undefined)
                return undefined;
            value = value[parts[index]];
        }
        return value;
    }

    function actualType(value) {
        if (value === null)
            return "null";
        if (Array.isArray(value))
            return "array";
        return typeof value;
    }

    var failures = [];
    var snapshot = { globals: {}, optionalGlobals: {}, probes: {} };
    requiredGlobals.forEach(function (entry) {
        var type = actualType(resolve(entry.name));
        snapshot.globals[entry.name] = type;
        if (type !== entry.type)
            failures.push(entry.name + ": expected " + entry.type + ", got " + type);
    });
    optionalGlobals.forEach(function (entry) {
        var type = actualType(resolve(entry.name));
        snapshot.optionalGlobals[entry.name] = type;
        if (type !== "undefined" && type !== entry.type)
            failures.push(entry.name + ": expected optional " + entry.type + ", got " + type);
    });
    probes.forEach(function (entry) {
        var type = actualType(resolve(entry.path));
        snapshot.probes[entry.path] = type;
        if (type !== entry.type)
            failures.push(entry.path + ": expected " + entry.type + ", got " + type);
    });

    console.log("[frida-surface][JSON] " + JSON.stringify(snapshot));
    if (failures.length !== 0)
        throw new Error("Frida surface mismatch:\n" + failures.join("\n"));
    console.log("[frida-surface][READY] compatibility surface verified");
})();
